In [43]:
import pandas as pd

df = pd.read_csv('../data/raw/raw.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   link           100 non-null    object
 1   nome           100 non-null    object
 2   preco          97 non-null     object
 3   nquartos       100 non-null    object
 4   nbanheiros     80 non-null     object
 5   ngaragem       95 non-null     object
 6   area           98 non-null     object
 7   data_scraping  100 non-null    object
dtypes: object(8)
memory usage: 6.4+ KB

In [44]:
df.head()

,link,nome,preco,nquartos,nbanheiros,ngaragem,area,data_scraping
0,https://sc.olx.com.br/florianopolis-e-regiao/i...,CASAS NO CAMPO DUNA,R$ 645.000,3,3,3,120m²,2025-09-05 19:42:48
1,https://sc.olx.com.br/florianopolis-e-regiao/i...,"Casas a partir de R$749.950,00 no Pedra Branca",R$ 745.950,2,3,2,90m²,2025-09-05 19:42:48
2,https://sc.olx.com.br/norte-de-santa-catarina/...,Duas casas em um terreno,R$ 450.000,375m²,NaN,NaN,NaN,2025-09-05 19:42:48
3,https://sc.olx.com.br/florianopolis-e-regiao/i...,Duas casas a venda em um terreno de 360 m2 Bai...,R$ 250.000,4,2,2,120m²,2025-09-05 19:42:48
4,https://sc.olx.com.br/florianopolis-e-regiao/i...,Casas com 5 dormitórios no Bairro Ipiranga em ...,R$ 900.000,5+,4,3,180m²,2025-09-05 19:42:48

In [45]:
df['preco'] = df['preco'].str.replace(r'[^\d]', '', regex=True)

df.head()

,link,nome,preco,nquartos,nbanheiros,ngaragem,area,data_scraping
0,https://sc.olx.com.br/florianopolis-e-regiao/i...,CASAS NO CAMPO DUNA,645000,3,3,3,120m²,2025-09-05 19:42:48
1,https://sc.olx.com.br/florianopolis-e-regiao/i...,"Casas a partir de R$749.950,00 no Pedra Branca",745950,2,3,2,90m²,2025-09-05 19:42:48
2,https://sc.olx.com.br/norte-de-santa-catarina/...,Duas casas em um terreno,450000,375m²,NaN,NaN,NaN,2025-09-05 19:42:48
3,https://sc.olx.com.br/florianopolis-e-regiao/i...,Duas casas a venda em um terreno de 360 m2 Bai...,250000,4,2,2,120m²,2025-09-05 19:42:48
4,https://sc.olx.com.br/florianopolis-e-regiao/i...,Casas com 5 dormitórios no Bairro Ipiranga em ...,900000,5+,4,3,180m²,2025-09-05 19:42:48

remover os cifroes dos precos

In [46]:
df.dropna()
df.replace(r'^\s*$', pd.NA, regex=True, inplace=True)
df.dropna(inplace=True)

remover os metros quadrados

In [47]:
df['area'] = df['area'].str.replace(r'[^\d,.]', '', regex=True)

df.head()

,link,nome,preco,nquartos,nbanheiros,ngaragem,area,data_scraping
0,https://sc.olx.com.br/florianopolis-e-regiao/i...,CASAS NO CAMPO DUNA,645000,3,3,3,120,2025-09-05 19:42:48
1,https://sc.olx.com.br/florianopolis-e-regiao/i...,"Casas a partir de R$749.950,00 no Pedra Branca",745950,2,3,2,90,2025-09-05 19:42:48
3,https://sc.olx.com.br/florianopolis-e-regiao/i...,Duas casas a venda em um terreno de 360 m2 Bai...,250000,4,2,2,120,2025-09-05 19:42:48
4,https://sc.olx.com.br/florianopolis-e-regiao/i...,Casas com 5 dormitórios no Bairro Ipiranga em ...,900000,5+,4,3,180,2025-09-05 19:42:48
5,https://sc.olx.com.br/florianopolis-e-regiao/i...,"Duas casas + 4 apartamentos à venda, a 50 metr...",1950000,5+,5+,5+,476,2025-09-05 19:42:48

retirar os +

In [50]:
df['nquartos'] = df['nquartos'].astype(str).str.replace('+', '', regex=False)
df['nbanheiros'] = df['nbanheiros'].astype(str).str.replace('+', '', regex=False)
df['ngaragem'] = df['ngaragem'].astype(str).str.replace('+', '', regex=False)


df.head()

,link,nome,preco,nquartos,nbanheiros,ngaragem,area,data_scraping
0,https://sc.olx.com.br/florianopolis-e-regiao/i...,CASAS NO CAMPO DUNA,645000,3,3,3,120,2025-09-05 19:42:48
1,https://sc.olx.com.br/florianopolis-e-regiao/i...,"Casas a partir de R$749.950,00 no Pedra Branca",745950,2,3,2,90,2025-09-05 19:42:48
3,https://sc.olx.com.br/florianopolis-e-regiao/i...,Duas casas a venda em um terreno de 360 m2 Bai...,250000,4,2,2,120,2025-09-05 19:42:48
4,https://sc.olx.com.br/florianopolis-e-regiao/i...,Casas com 5 dormitórios no Bairro Ipiranga em ...,900000,5,4,3,180,2025-09-05 19:42:48
5,https://sc.olx.com.br/florianopolis-e-regiao/i...,"Duas casas + 4 apartamentos à venda, a 50 metr...",1950000,5,5,5,476,2025-09-05 19:42:48

salvar

In [52]:
df.to_csv('../data/processed/data.csv', index=False)